############################################################
#
# web访问端口号配置  约定:8088
# 端口占用 tasklist|findstr "8088"
#
############################################################
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 80KB           # 可以看源码是哪个版本弃用

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.72.153:3306/online?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    hikari:                                 # 默认配置可以查看 HikariConfig
      pool-name: hikariCP
      minimum-idle: 5                       # 最小连接数
      maximum-pool-size: 15                 # 最大连接数
      auto-commit: true                     # 自动提交
      idle-timeout: 30000                   # 连接超时的最大时长(毫秒),超时则被释放(retried),默认10分钟
      max-lifetime: 1800000
      connection-timeout: 30000             # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没有获取可用的连接，则发生SQLException，默认30秒
      connection-test-query: SELECT 1



############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.luxshare.pojo  # 所有POJO类所在的包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出日志(生产时关闭)


############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL     # 默认是 MYSQL
  safe-delete: true   # 配置为 true 后，delete 和 deleteByExample 都必须设置查询条件才能删除，否则会抛出异常
  safe-update: true   # 配置为 true 后，updateByExample 和 updateByExampleSelective 都必须设置查询条件才能删除，否则会抛出异常
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

############################################################
#
# 日志设定
#
############################################################

logging:
  level:
    root: info
#    org.springframework.web.servlet.mvc.method.annotation: trace
#    com.luxshare.interceptors.PerformanceInterceptor: debug # 生产中使用有一定的性能损耗,仅用于调试与测试环境