#################################################
#
# 配置数据源信息
#
#################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.72.153:3306/online?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    hikari:                                 # 默认配置可以查看 HikariConfig
      pool-name: hikariCP
      minimum-idle: 5                       # 最小连接数
      maximum-pool-size: 50                 # 最大连接数
      auto-commit: true                     # 自动提交
      idle-timeout: 30000                   # 连接超时的最大时长(毫秒),超时则被释放(retried),默认10分钟
      max-lifetime: 1800000
      connection-timeout: 30000             # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没有获取可用的连接，则发生SQLException，默认30秒
      connection-test-query: SELECT 1



#################################################
#
# mybatis 配置
#
#################################################
mybatis:
  type-aliases-package: com.luxshare.pojo  # 所有POJO类所在的包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件



#################################################
#
# web访问端口号配置  约定:8088
#
#################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 80KB           # 可以看源码是哪个版本弃用



#################################################
#
# 日志设定
#
#################################################

logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation: trace